#:schema node_modules/wrangler/config-schema.json

name = "typeonline-next"
main = ".open-next/worker.js"
compatibility_date = "2025-12-01"
compatibility_flags = ["nodejs_compat"]

# Uncomment to configure custom domain or routes:
# routes = [{ pattern = "typeonline.uk", custom_domain = true }]

# Static assets served from the edge
[assets]
directory = ".open-next/assets"
binding = "ASSETS"
