export const runtime = 'edge';

import type { Metadata } from "next";
// import { Inter } from "next/font/google";
import "./globals.css";

// const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
    title: "typeonline - free online touch typing course",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {

    return (
        <html lang="en">
            <body >
                <div id="header">
                    <h1><a href="/"><span>learn to type online...</span><br/>typeonline.uk</a></h1>
                </div>
                {children}
                <div id="footer">
                    <p id="updated"><strong>Last updated:</strong> 20th August 2024</p>
                    <p id="copyright">&copy; Dave Bartlett 2004-2018</p>
                </div>
            </body>
        </html>
    );
}
